name: doc

on:
  workflow_dispatch:

jobs:
  doc:
    name: Build documents and publish
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install poetry sphinx
          python -m pip install poetry-dynamic-versioning
          poetry install
      - name: Publish with Sphinx
        run: |
          sphinx-apidoc -e -o ./docs/generated -t ./docs/template/ src/jptranstokenizer
          sphinx-build ./docs ./docs/build -c ./docs/ -T
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/